### ISSUE TITLE
no such pattern

### ISSUE THREAD

**Issue by skynet594** [1ndianl33t/Gf-Patterns#1]
When i run the tool according to the usage instruction in the READ me file i get an error message which says "no such pattern". Any help??

**Comment by skynet594** [comment]
Sorry for the comment i didn't  get the instructions clearly but i got it now..

**Comment by Princ3g** [comment]
> Sorry for the comment i didn't get the instructions clearly but i got it now..

Can you please share the instructions, as I'm facing the same problem. TIA

**Comment by zinminphyo0** [comment]
@Princ3g 
Try this
`git clone https://github.com/1ndianl33t/Gf-Patterns`
`mkdir .gf`
`mv ~/Gf-Patterns/*.json ~/.gf`

**Comment by A91K3C1l** [comment]
@zinminphyo0 
Tq brother

**Comment by 3386893054** [comment]
"style="position:fixed;top:0;left:0;border:999em solid green;" onmouseover="alert(document.domain)"
{{_c.constructor('alert(1)')()}}
{{constructor.constructor('alert(1)')()}}

"style="position:fixed;top:0;left:0;border:999em solid green;" onmouseover="alert(document.domain)"
{{_c.constructor('alert(1)')()}}
{{constructor.constructor('alert(1)')()}}["style="position:fixed;top:0;left:0;border:999em solid green;" onmouseover="alert(document.domain)"
{{_c.constructor('alert(1)')()}}
{{constructor.constructor('alert(1)')()}}]("style="position:fixed;top:0;left:0;border:999em solid green;" onmouseover="alert(document.domain)"
{{_c.constructor('alert(1)')()}}
{{constructor.constructor('alert(1)')()}})

**Comment by 3386893054** [comment]
<h1>sacac</h1>

**Comment by Captain09-cdm** [comment]
> @Princ3g Try this `git clone https://github.com/1ndianl33t/Gf-Patterns` `mkdir .gf` `mv ~/Gf-Patterns/*.json ~/.gf`
> 
> Sloved

for me not sloveing why can you help me please

**Comment by ARTICFOX1234** [comment]
I saw a video in nahamsec he is using gf servers but I cant do this

**Comment by bacoke** [comment]
> > Sorry for the comment i didn't get the instructions clearly but i got it now..
> 
> Can you please share the instructions, as I'm facing the same problem. TIA
