### ISSUE TITLE
no such pattern ( Go tools Install as Binary ) 

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [1ndianl33t/Gf-Patterns#10]
Hello 

wayback & gf  tools  are placed in /usr/local/bin  
I mv the gf files to the same directory  but  got the safe error

Any solution, please ?? 

Thanks

**Comment by gh0sh** [comment]
Read the readme how to install gf..check your ~/.gf folder if not exist create one then copy .json files to that folder.

**Comment by pankajninjasec** [comment]
still have same problem

**Comment by pankajninjasec** [comment]
p@kali:~/.gf$ gf ssrf 
grep: .: Is a directory
p@kali:~/.gf$ 
i get this error , i placed json file in ~/.gf directory but still have this problem

**Comment by gh0sh** [comment]
try this command:
cat <text-files> | gf ssrf         #replace <text-files> with files you want to search for the pattern

**Comment by dd404x** [comment]
I need help, I have the same problem，I use ‘cat | gf ssrf waybackdata’ and nothing will be output.
It seems that grep called by gf treats text files as binary files.
![截图20200908172052636](https://user-images.githubusercontent.com/19923974/92458335-d15d7300-f1f7-11ea-8f29-644c4dcca177.jpg)

**Comment by gh0sh** [comment]
try this command: 
echo "bugcrowd.com" | gau | tee -a output.txt | gf ssrf  --> if working then your gf is not a problem..maybe the file mggau.txt not contain ssrf pattern.

PS: Don't forget install gau (go get -u github.com/lc/gau)

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/92481809-72105a80-f219-11ea-83af-0b13941ea62b.png)
![image](https://user-images.githubusercontent.com/19923974/92482004-b13eab80-f219-11ea-8a57-ddc5c756beef.png)
![image](https://user-images.githubusercontent.com/19923974/92482116-d501f180-f219-11ea-8ba3-71326c4a2e27.png)
It’s strange, is there a problem with my mggua file, grep always treats it as a binary file?

**Comment by dd404x** [comment]
Thank you, it seems that there is no problem when gf and gua are used at the same time

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/92484893-ce28ae00-f21c-11ea-8c0a-de32aa58ef0f.png)
Thanks again, I seem to use gf to find ssrf

**Comment by Deku-izuku-dotcom** [comment]
Thanks a Lot  
The solution  Work for me
